name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch: # manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: KasmyrA
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-dark-purple.gif?palette=github-dark&color_snake=#10ad28&color_dots=#e4ebc3,#4c1d95,#6d28d9,#7c3aed,#c084fc

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
